#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Thu Mar 01 12:30:40 IST 2018
apiSecret=8044fbca5fc992194fa0c07fc652e57891407094984a24bc8bc2ad8c387ee8d3
